#********** TESTS *********#

PUT http://localhost:8000/reset/password/stacknewbie@gmail.com
Content-Type: application/json
# token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYWFmYWUxOS04ZDE1LTQ1NWItYTFhNi0yYWViNzc1MzRjODgiLCJlbWFpbCI6InN0YWNrbmV3YmllQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ik51ciIsImxhc3ROYW1lIjoiT21vbmRpIiwiaXNEZWxldGVkIjowLCJpc0FkbWluIjowLCJlbWFpbHNSZWNlaXZlZCI6MCwiaWF0IjoxNjg0NDE2ODQzLCJleHAiOjE2ODQ3NzY4NDN9.qIzYKA14dxaUvqprYLkj7zBafVwUAs92yNSFY-4BVI0


{
    "email": "stacknewbie@gmail.com",
    "userPassword": "newPWD2023#"
}

# newPWD2024#

# ADMIN EMAIL : admin@gmail.com
# ADMIN PASSWORD : adminUSER2023@#

##### REQUEST FOR PASSWORD RESET | When a user is redirected to this page, 
#       a new token is assigned to them       
#
#                **Password Reset Page**
#
#               Email: __________________
#       
#                 ********************
#                 |   RESET BUTTON   |
#                 ********************
# 
# THE FOLLOWING REQUEST WITH SEND AN EMAIL WITH A RESET LINK
GET http://localhost:8000/reset/stacknewbie@gmail.com
