#*************************************#
#*********** USER REQUESTS ***********#
#*************************************#

########### GET USER BY ID #############
GET http://localhost:4000/users/bee2f213-39d2-42a3-990c-f9836fbb848e


########### GET ALL USERS #############
GET http://localhost:4000/users


########### ADD A USER #############
POST http://localhost:4000/users
Content-Type: application/json

{
    "email":"jonathanndambuki@gmail.com",
    "userPassword":"M4nch3st3r4Lyf",
    "firstName":"Jonathan",
    "lastName":"Ndambuki",
    "streetAddress":"Baga Toiruu",
    "city":"Ulaanbaatar",
    "country":"Asia",
    "phone":"99-628616"
}


########### UPDATE USER #############
PUT http://localhost:4000/users/0aafae19-8d15-455b-a1a6-2aeb77534c88
Content-Type: application/json

{
    "email":"stacknewbie@gmail.com",
    "userPassword":"MoF9h{0};~!",
    "firstName":"Nur",
    "lastName":"Omondi",
    "streetAddress":"Karen Rd.",
    "city":"Nairobi",
    "country":"Kenya",
    "phone":"0788783652"
}


######## DELETE USER ###########
DELETE http://localhost:4000/users/1212o2331


######## LOGIN USER ###########
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "jonathanndambuki@gmail.com",
    "userPassword": "M4nch3st3r4Lyf"
}

#************* END | USERS  ************#
                                       
#             WHITE SPACE               #
                                       
#***************************************#
#********** PRODUCT REQUESTS ***********#
#***************************************#

######### ADD PRODUCT ###########
POST http://localhost:4000/products
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NzA2NWYwMy05NTgwLTQ2ZDAtOTBhNi01NmMxZWRlNmYwZTkiLCJlbWFpbCI6ImpvbmF0aGFubmRhbWJ1a2lAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiSm9uYXRoYW4iLCJsYXN0TmFtZSI6Ik5kYW1idWtpIiwiaXNEZWxldGVkIjowLCJpc0FkbWluIjowLCJlbWFpbHNSZWNlaXZlZCI6MCwiaWF0IjoxNjg0OTYwNTg5LCJleHAiOjE2ODUzMjA1ODl9._nizBVUJkqXqZojspt4thdNpC4YPMe0N7ex9pWsxFq0

{
    "productName": "Steam Deck", 
    "productImage": "https://www.digitaltrends.com/wp-content/uploads/2021/07/e6wi5ghuyaahvkt.jpg?fit=720%2C720&p=1",
    "productDescription": "Who it's for: Players looking for console-like performance and selection on the go.",
    "category": "Gaming",
    "price": 400
}

# {
#     "productName": "Iphone X",
#     "productImage": "https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/SP770/iphonex.png",
#     "productDescription": "The definition of innovation.",
#     "price": 10000
# }


######### DELETE PRODUCT ##########
DELETE http://localhost:4000/products/12222

######## UPDATE PRODUCT ###########
PUT http://localhost:4000/products/8516b2ff-6dd4-48d0-b6f3-b94511fea530
Content-Type: application/json

{
    "productName": "Magic Mouse - Black Multi-Touch Surface", 
    "productImage": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MMMQ3?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1645138486301",
    "productDescription": "Magic Mouse is wireless and rechargeable, with an optimized foot design that lets it glide smoothly across your desk.",
    "category": "Desktop",
    "price": 99
}

# { 
#     "productName": "AirPods (3rd generation)", 
#     "productImage": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MME73?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1632861342000",
#     "productDescription": "(3rd generation) with MagSafe Charging Case.",
#     "category": "Mobile",
#     "price": 179
# }


######### GET ALL PRODUCTS ##########
GET http://localhost:4000/products

####### GET PRODUCT BY ID ########
GET http://localhost:4000/products/90206c5b-ade3-42f0-8381-1f3a64d056b7
#************ END | PRODUCTS  ************#


#++++++++++++++++++++++++++++++++++++#
############### ORDERS ###############
#++++++++++++++++++++++++++++++++++++#
POST http://localhost:4000/orders
Content-Type: application/json

{
	"orderDate": "6/4/2023",
	"totalAmount": 2000
}